import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ENV, UseActionProvider, getUseActionProviderValue } from "use-action";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

console.log({ ENV });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout(
	props: Readonly<{
		children: React.ReactNode;
	}>,
) {
	const value = getUseActionProviderValue();
	return (
		<UseActionProvider value={value}>
			<html lang="en">
				<body className={inter.className}>
					{props.children}

					<Toaster />
				</body>
			</html>
		</UseActionProvider>
	);
}
