import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { UseActionProvider, getRequestStorage } from "use-action";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout(
	props: Readonly<{
		children: React.ReactNode;
	}>,
) {
	const formData = getRequestStorage().formData;

	return (
		<UseActionProvider
			value={
				formData
					? {
							formData,
						}
					: null
			}
		>
			<html lang="en">
				<body className={inter.className}>
					{props.children}

					<Toaster />
				</body>
			</html>
		</UseActionProvider>
	);
}
